version: '3.8'

services:
  pet-memorial:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
    environment:
      - STABILITY_API_KEY=${STABILITY_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY} 